### PR TITLE
Edge properties for reasonable edge classification 📊 

### LINKED ISSUE #220: [DEVELOPMENT] Utilise `edge_attr` in graph convolutions
Source information [here](https://github.com/pyg-team/pytorch_geometric/issues/668)

### LINKED ISSUE #247: [DEVELOPMENT] How to set a global config with different font attributes in matplotlib?
I'm looking for an equivalent global config as the logger has:

https://github.com/alan-turing-institute/grace/blob/bd91bdffe0aa3ad3ed6bab0f97cb1d90f0b37ad2/grace/logger.py#L4-L8

Something in the line of this snippet, which would be defined once (probably in `run.py`) and inherited all over the pipeline:
```
font = {'family' : 'normal',
        'weight' : 'bold',
        'size'   : 22}

matplotlib.rc('font', **font)
```
Any suggestions?

### LINKED ISSUE #278: [DEVELOPMENT] Use distance / weighting as feature for edge embedding learning
**Describe the issue here**

### LINKED ISSUE #281: [DEVELOPMENT] Allow specifying variable number of graph conv & dense linear layers

### LINKED ISSUE #284: [DEVELOPMENT] Store edge properties in `Data` object for training
**Describe the issue here**

### LINKED ISSUE #291: Add more sophisticated classifier model options
Remove the placeholder for other classifier model options. As soon as I'm done with edge property calculation, I can extend the model options to other architectures (I'm unsure how to design this properly tho, to avoid unnecessary code duplication).

_Originally posted by @KristinaUlicna in https://github.com/alan-turing-institute/grace/pull/283#discussion_r1345530374_

### LINKED ISSUE #294: [FEATURE REQUEST] Consider visualising the edge properties in the dataset
To make sure your properties are of reasonable ranges / bounds / distributions, consider plotting out their histograms.

### LINKED ISSUE #303: [DEVELOPMENT] Compute edge properties
https://github.com/alan-turing-institute/grace/blob/b59c4d5df6bdd4c41b76cfefa9e364816a4469b1/grace/base.py#L93-L160

### LINKED ISSUE #304: [DEVELOPMENT] Define an `EdgePropertyCruncher`
Implementation here:

https://github.com/alan-turing-institute/grace/blob/b59c4d5df6bdd4c41b76cfefa9e364816a4469b1/grace/models/property_cruncher.py#L7-L19

### PR DESCRIPTION
**Pull request by KristinaUlicna**
## PR contribution summary

**Why is this PR useful / good for?** *Please describe the problem(s) you're trying to address.*
* Computes, stores & organises a set of geometrical `EdgeProperties`
* Implements edge properties into the classifier training 
* Extends available model catalogue by those which input edge properties
* Implements the architecture for Graph Attention Network (GAT)
* Allows [multi-head] attention visualisation to monitor training progress
* Adds additional config hyperparameters to keep up with the progress

### List of proposed changes / linked issues & discussions

- [x] ✅ Resolves #303 
- [x] ✅ Resolves #304
- [x] ✅ Resolves #291 ▶️ includes GAT model which computes edge attention weights based on edge properties
- [x] ✅ Resolves #284 ▶️ `datasets.py`
- [x] ✅ Resolves #281 ▶️ `classifier.py`
- [x] ✅ Resolves #294 ▶️ via `edge_properties.ipynb`
- [x] ✅ Fixes #247 with `seaborn` import from `styling` in relevant `__init__.py` 
- [x] ✅ Closes #220
- [x] ✅ Closes #278

### What should a reviewer concentrate their feedback on?

+ 🏃 Scripts to run - reproducing training results
+ 💻 Code quality

#### What type of PR is this? (check all applicable)

+ 🪄 Feature
+ #️⃣ Documentation / code annotation
+ 🧑‍💻 Code refactor / style
+ 🔥 Performance Improvements

#### Added tests?

+ 🙅 no, temporarily silenced some due to lack of graph attributes

---

## PR review summary

Describe what this PR does & **how you reviewed** the individual items, where needed:

* <TEXT>

*Some helper checks to tick off:*

* Focus on image annotation
* Focus on model training
* Could any optimization be applied?
* Is there any redundant code?
* Are there any spelling errors?

**In conclusion**, after my review, I'd like to:

* 🙋 ask some clarifying questions
* 🙅 suggest some specific changes

### CODE REVIEW

**Comment by crangelsmith** [comment]
I think you can skip tests without having to comment them out with some of these options https://docs.pytest.org/en/7.3.x/how-to/skipping.html

**Comment by KristinaUlicna** [comment]
Thanks for the suggestion - this is gold 🥇 ! All failing tests are now re-implemented in PR #308 (which extends the failing run if no edge properties are created)

**Comment by crangelsmith** [comment]
Run the training (after calculating node and edge properties beforehand), I get the following results:

MRC_Synthetic_File_006-Whole_Graph_Visualisation
MRC_Synthetic_File_006-Optimised_Components


I think this is compatible with @KristinaUlicna results :)

**Comment by crangelsmith** [comment]
My main suggestions (mostly discussed offline with @KristinaUlicna) are being implemented in the following PRs, so happy to approve this one.

**Review by crangelsmith — APPROVED** [review]

**Pull request merged**
