### PR TITLE
Install GRACE from conda environment

### LINKED ISSUE #5: Add documentation

### LINKED ISSUE #11: Check that we can install the package
Might need to add some instructions, as part of #10 for `pytorch`, `pytorch-geometric` and `CVXOPT`

### LINKED ISSUE #108: [BUG] Napari binarises synthetic images
**Describe the bug**

I've created a dataset full of synthetic images where the entire image is set to value = 'grey' (127 for integer `dtype`, 0.5 for float `dtype`) and the squares under each node are set to the corresponding value: 'black' (0) for true negative nodes and 'white' (255 or 1.0) for true positive, object belonging nodes. I save these images as `mrc` files & check that their values are correct. 

In the napari annotator, the images are visualised as binary, i.e. only two colours in the black-and-white masks. Changing the 
``` 
with mrcfile.open(IMAGE_PATH, "r") as mrc:
    # image_data = mrc.data.astype(int)
    image_data = mrc.data 
```
^^^ Switching the `astype(int)` off or changing it to `astype(float)` doesn't help. Why is the annotator binarising the images? How can I turn this off?

image
Screenshot 2023-06-20 at 11 18 59

### PR DESCRIPTION
**Pull request by KristinaUlicna**
- [x] Created an installable conda environment thanks to @marjanfamili 🚀 
- [x] Specified package installation instructions in README.md - resolves #5 & fixes #11 
- [x] Helps with napari showing data of different type than just integers - resolves #108

### CODE REVIEW

**Comment by mooniean** [comment]
I'm starting the review. I'm struggling to even just create the conda environment, as it spends a long time examining and solving conflicts.

**Comment by quantumjot** [comment]
I think that the `environment.yml` could be pared down. There's a lot of packages in there that probably aren't required for GRACE

**Comment by mooniean** [comment]
It's a conda issue too apparently (https://github.com/conda/conda/issues/10034) so I'll try their solutions, see which conflicts there are (because it does find conflicts, just gets stuck in a loop of finding the incompatible packages)

**Comment by marjanfamili** [comment]
Im happy to produce this `environment.yml ` again if helpful.

**Review by mooniean — APPROVED** [review]
LGTM

**Comment by marjanfamili** [comment]
The conda environment was failing as it had the version of build (computer architecture specific in the environment). This can be avoided by using `conda env export --no-builds`

**Comment by mooniean** [comment]
The packages were showing differences like, for example:

`seaborn found but mismatch. Specification pkg: seaborn==0.12.2=hd8ed1ab_0, Running pkg: seaborn==0.12.2=pypi_0`

**Pull request merged**
